export const SET_LOADING_SCREEN = 'SET_LOADING_SCREEN';
export const SET_LOAD_ELDERLYREADING_SCREEN = 'SET_LOAD_ELDERLYREADING_SCREEN';
export const SET_USER_PROFILE = 'SET_USER_PROFILE';
export const LOGOUT = 'LOGOUT';
export const SET_UPCOMING_ACTIVITIES = 'SET_UPCOMING_ACTIVITIES';
export const SET_PAST_ACTIVITIES = 'SET_PAST_ACTIVITIES';
export const SET_NEW_ALERTS = 'SET_NEW_ALERTS';
export const SET_ATTENDED_ALERTS = 'SET_ATTENDED_ALERTS';